complaints/urls.py
from django.conf.urls import url

from . import views

app_name = 'complaints'
urlpatterns = [
    url(r'^$', views.ComplaintView.as_view(), name='complaint'),
]

compliments/urls.py
from django.conf.urls import url

from . import views

app_name = 'compliments'
urlpatterns = [
    url(r'^$', views.ComplimentView.as_view(), name='compliment'),
]

compliments_and_complaints/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="home.html"), name='home'),
    url(r'^thanks/$', TemplateView.as_view(template_name='thanks.html'), name='thanks'),
    url(r'^complaints/', include('complaints.urls')),
    url(r'^compliments/', include('compliments.urls')),
    url(r'^admin/', admin.site.urls),
]

complaints/models.py
from __future__ import unicode_literals

from django.db import models

class Complaint(models.Model):
    message = models.TextField()
    publication_date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.message

compliments/models.py
from __future__ import unicode_literals

from django.db import models

class Compliment(models.Model):
    message = models.TextField()
    publication_date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.message

complaints/forms.py
# coding=utf-8
from django import forms

from .models import Complaint

class ComplaintForm(forms.Form):
    message = forms.CharField(label="Поплака", widget=forms.Textarea)

compliments/forms.py
# coding=utf-8
from django import forms

from .models import Compliment

class ComplimentForm(forms.Form):
    message = forms.CharField(label="Пофалба", widget=forms.Textarea)

complaints/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import View

from .forms import ComplaintForm
from .models import Complaint

class ComplaintView(View):
    def get(self, request):
        return render(request, 'complaints/complaint.html', {'form': ComplaintForm()})

    def post(self, request):
        form = ComplaintForm(request.POST)
        if form.is_valid():
            Complaint.objects.create(message=form.cleaned_data['message'])
            return HttpResponseRedirect(reverse('thanks'))
        else:
            return render(request, 'complaints/complaint.html', {'form': ComplaintForm()})

compliments/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import View

from .forms import ComplimentForm
from .models import Compliment

class ComplimentView(View):
	def get(self, request):
		return render(request, 'compliments/compliment.html', {'form': ComplimentForm()})

	def post(self, request):
		form = ComplimentForm(request.POST)
		if form.is_valid():
			Compliment.objects.create(message=form.cleaned_data['message'])
			return HttpResponseRedirect(reverse('thanks'))
		else:
			return render(request, 'compliments/compliment.html', {'form': ComplimentForm()})

complaints/templates/complaints/complaint.html
<form action={% url 'complaints:complaint' %} method="post">
    {% csrf_token %}
    {{ form.message.label }}
    <br>
    {{ form.message }}
    <p><input type="submit" value="Поднеси поплака"></p>
</form>

compliments/templates/compliments/compliment.html
<form action={% url 'compliments:compliment' %} method="post">
    {% csrf_token %}
    {{ form.message.label }}
    <br>
    {{ form.message }}
    <p><input type="submit" value="Поднеси пофалба"></p>
</form>

templates/home.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>РСМ Македонија пофалби и поплаки</title>
    </head>
    <body>
        <h1>Добредојдовте на страната на РСМ Македонија за пофалби и поплаки</h1>
        <h2>
            <a href="{% url 'complaints:complaint' %}">Поднесете поплака</a>
        </h2>
		<h2>
            <a href="{% url 'compliments:compliment' %}">Поднесете пофалба</a>
        </h2>
    </body>
</html>

templates/thanks.html
<p>Благодариме на вашата повратна информација.</p>
<p><a href="{% url 'home' %}">Вратете се дома</a></p>